// Elenco stati (in italiano) per la select "Stato" del form Contatti.
// Ordine alfabetico. Modificabile qui se serve aggiungere/togliere una voce.
export const countries = [
  "Afghanistan", "Albania", "Algeria", "Andorra", "Angola", "Antigua e Barbuda",
  "Arabia Saudita", "Argentina", "Armenia", "Australia", "Austria", "Azerbaigian",
  "Bahamas", "Bahrein", "Bangladesh", "Barbados", "Belgio", "Belize", "Benin",
  "Bhutan", "Bielorussia", "Bolivia", "Bosnia ed Erzegovina", "Botswana", "Brasile",
  "Brunei", "Bulgaria", "Burkina Faso", "Burundi", "Cambogia", "Camerun", "Canada",
  "Capo Verde", "Ciad", "Cile", "Cina", "Cipro", "Colombia", "Comore",
  "Congo (Rep. del)", "Congo (Rep. Dem. del)", "Corea del Nord", "Corea del Sud",
  "Costa d'Avorio", "Costa Rica", "Croazia", "Cuba", "Danimarca", "Dominica",
  "Ecuador", "Egitto", "El Salvador", "Emirati Arabi Uniti", "Eritrea", "Estonia",
  "Eswatini", "Etiopia", "Figi", "Filippine", "Finlandia", "Francia", "Gabon",
  "Gambia", "Georgia", "Germania", "Ghana", "Giamaica", "Giappone", "Gibuti",
  "Giordania", "Grecia", "Grenada", "Guatemala", "Guinea", "Guinea-Bissau",
  "Guinea Equatoriale", "Guyana", "Haiti", "Honduras", "India", "Indonesia", "Iran",
  "Iraq", "Irlanda", "Islanda", "Isole Marshall", "Isole Salomone", "Israele",
  "Italia", "Kazakistan", "Kenya", "Kirghizistan", "Kiribati", "Kuwait", "Laos",
  "Lesotho", "Lettonia", "Libano", "Liberia", "Libia", "Liechtenstein", "Lituania",
  "Lussemburgo", "Macedonia del Nord", "Madagascar", "Malawi", "Malaysia", "Maldive",
  "Mali", "Malta", "Marocco", "Mauritania", "Mauritius", "Messico", "Micronesia",
  "Moldova", "Monaco", "Mongolia", "Montenegro", "Mozambico", "Myanmar (Birmania)",
  "Namibia", "Nauru", "Nepal", "Nicaragua", "Niger", "Nigeria", "Norvegia",
  "Nuova Zelanda", "Oman", "Paesi Bassi", "Pakistan", "Palau", "Panama",
  "Papua Nuova Guinea", "Paraguay", "Perù", "Polonia", "Portogallo", "Qatar",
  "Regno Unito", "Repubblica Ceca", "Repubblica Centrafricana", "Repubblica Dominicana",
  "Romania", "Ruanda", "Russia", "Saint Kitts e Nevis", "Saint Lucia",
  "Saint Vincent e Grenadine", "Samoa", "San Marino", "São Tomé e Príncipe", "Senegal",
  "Serbia", "Seychelles", "Sierra Leone", "Singapore", "Siria", "Slovacchia",
  "Slovenia", "Somalia", "Spagna", "Sri Lanka", "Stati Uniti d'America", "Sudafrica",
  "Sudan", "Sudan del Sud", "Suriname", "Svezia", "Svizzera", "Tagikistan", "Taiwan",
  "Tanzania", "Thailandia", "Timor Est", "Togo", "Tonga", "Trinidad e Tobago",
  "Tunisia", "Turchia", "Turkmenistan", "Tuvalu", "Ucraina", "Uganda", "Ungheria",
  "Uruguay", "Uzbekistan", "Vanuatu", "Città del Vaticano", "Venezuela", "Vietnam",
  "Yemen", "Zambia", "Zimbabwe",
];
